### ISSUE TITLE
hc scaffold entry-type broken for me on 0.3.1 

### ISSUE THREAD

**Issue by tibetsprague** [holochain/scaffolding#328]
After going through the whole questionnaire it crashes every time with 

`thread 'main' panicked at src/scaffold/entry_type/integrity.rs:436:30: Extern function must have one argument`

I'm on macOS Sonoma using holochain_cli 0.3.1

**Comment by c12i** [comment]
Thanks for reporting this. I think I might have an idea what could have caused this. 

`#[hdk_extern]` annotated functions can now be parameterless if they don't expect any typed arguments to be passed (reference: https://github.com/holochain/holochain/pull/3441), scaffolded code was updated to match this. Looks like the problematic code here still expects this function to always contain a parameter.

> After going through the whole questionnaire it crashes every time with

I can look into this, although providing the exact cli commands you ran to get this error could help me reproduce this.

**Comment by tibetsprague** [comment]
hmm I'm using `hc scaffold entry-type` which is from holochain_cli 0.3.1, is there a different way to run hc-scaffold?

**Comment by tibetsprague** [comment]
my exact command is 

```
hc scaffold entry-type
✔ Entry type name (snake_case): · contact
✔ Multiple integrity zomes were found in DNA relay, choose one: · relay_integrity

Which fields should the entry contain?

✔ Choose field type: · AgentPubKey
✔ Should a link from the AgentPubKey provided in this field also be created when entries of this type are created? · yes
✔ Which role does this agent play in the relationship ? (eg. "creator", "invitee") · contact
✔ Field name: · public_key

✔ Choose field type: · String
✔ Field name: · name
✔ Should this field be visible in the UI? · no

✔ Choose field type: · String
✔ Field name: · avatar
✔ Should this field be visible in the UI? · no

Chosen fields: public_key, name, avatar

✔ Which CRUD functions should be scaffolded (SPACE to select/unselect, ENTER to continue)? · Update, Delete
✔ Should a link from the original entry be created when this entry is updated? · Yes (more storage cost but better read performance, recommended)
```

**Comment by c12i** [comment]
> 
hmm I'm using hc scaffold entry-type which is from holochain_cli 0.3.1, is there a different way to run hc-scaffold?

Yes, you can either run `hc scaffold --version` or `hc-scaffold --version` both should get the current version of the cli

**Comment by tibetsprague** [comment]
`hc-scaffold --version` returns `holochain_scaffolding_cli 0.3000.0`

**Comment by c12i** [comment]
Thanks for your patience. I have just released a fix for this issue. The fix is currently available only on holonix, so you'll need to run `nix flake update` to get it. Please let me know if you continue to experience any problems.

I plan to make a crates.io release tomorrow, but I'm currently blocked by issue #320.

**Comment by tibetsprague** [comment]
hmm still getting the error after doing `nix flake update`. should I be seeing a different version of scaffold than 0.3000.0?

my flake.nix looks like this:

```
{
  description = "Template for Holochain app development";

  inputs = {
    p2p-shipyard.url = "github:darksoil-studio/p2p-shipyard";
    holochain-nix-versions.url =
      "github:holochain/holochain/?dir=versions/0_3";
    holochain-flake = {
      url = "github:holochain/holochain";
      inputs.versions.follows = "holochain-nix-versions";
    };

    nixpkgs.follows = "holochain-flake/nixpkgs";
    flake-parts.follows = "holochain-flake/flake-parts";
  };

  outputs = inputs@{ flake-parts, holochain-flake, ... }:
    flake-parts.lib.mkFlake {
      specialArgs.nonWasmCrates = [ "relay" ];
      inherit inputs;
    } {
      systems = builtins.attrNames holochain-flake.devShells;
      perSystem = { config, pkgs, system, inputs', ... }: {
        devShells.default = pkgs.mkShell {
          inputsFrom = [
            inputs'.p2p-shipyard.devShells.holochainTauriDev
            holochain-flake.devShells.${system}.holonix
          ];
          packages = [ pkgs.nodejs-18_x ];
        };
        devShells.androidDev = pkgs.mkShell {
          inputsFrom = [
            inputs'.p2p-shipyard.devShells.holochainTauriAndroidDev
            holochain-flake.devShells.${system}.holonix
          ];
          packages = [ pkgs.nodejs-18_x ];
        };
      };
    };
}
```

**Comment by c12i** [comment]
Strange, the new version should be `holochain_scaffolding_cli 0.3000.1`

**Comment by tibetsprague** [comment]
Stranger yeah its still giving me the older version

**Comment by ThetaSinner** [comment]
Best guess is that the double "inputsFrom` is getting a locked Holonix from darksoil. Is this the flake that they are recommending somewhere? 

In the `flake.lock` I see a "scaffolding" input at `a0cb33880fec6d1a1ad6e7f584ca2642409f1d4e` and a "scaffolding_2" input at `ea8dfd8ed4778184338edd3549711f94e70f780e`. So there are two versions of scaffolding present.

**Comment by tibetsprague** [comment]
hmm, this is what was recommended for using the new darksoil p2p-shipyard framework for deploying Holochain on android with Tauri mobile. Maybe I need to get them to update something. In the meantime I was able to manually find the updated hc-scaffold-0.3000.1 bin in /nix/store and run that and it worked! so thank you

**Comment by ThetaSinner** [comment]
@tibetsprague If you want a Nix solution, this should work for you:

```
{
  description = "Template for Holochain app development";

  inputs = {
    p2p-shipyard = {
      url = "github:darksoil-studio/p2p-shipyard";
      inputs.holochain.follows = "holochain-flake";
      inputs.versions.follows = "holochain-nix-versions";
    };
    holochain-nix-versions.url =
      "github:holochain/holochain/?dir=versions/0_3";
    holochain-flake = {
      url = "github:holochain/holochain";
      inputs.versions.follows = "holochain-nix-versions";
    };

    nixpkgs.follows = "holochain-flake/nixpkgs";
    flake-parts.follows = "holochain-flake/flake-parts";
  };

  outputs = inputs@{ flake-parts, holochain-flake, ... }:
    flake-parts.lib.mkFlake {
      specialArgs.nonWasmCrates = [ "relay" ];
      inherit inputs;
    } {
      systems = builtins.attrNames holochain-flake.devShells;
      perSystem = { config, pkgs, system, inputs', ... }: {
        devShells.default = pkgs.mkShell {
          inputsFrom = [
            inputs'.p2p-shipyard.devShells.holochainTauriDev
            holochain-flake.devShells.${system}.holonix
          ];
          packages = [ pkgs.nodejs-18_x ];
        };
        devShells.androidDev = pkgs.mkShell {
          inputsFrom = [
            inputs'.p2p-shipyard.devShells.holochainTauriAndroidDev
            holochain-flake.devShells.${system}.holonix
          ];
          packages = [ pkgs.nodejs-18_x ];
        };
      };
    };
}
```

So I'm just replacing `p2p-shipyard.url = "github:darksoil-studio/p2p-shipyard";` with:

```
p2p-shipyard = {
      url = "github:darksoil-studio/p2p-shipyard";
      inputs.holochain.follows = "holochain-flake";
      inputs.versions.follows = "holochain-nix-versions";
    };
```

You could think of this like saying "I want the p2p shipyard, but I will decide what version of Holochain I used in the shipyard". So then the versions you see in your shell and the versions used by the shipyard will match and hopefully everything will be more consistent!

The only thing to be careful of like this is that if you upgrade to a version of Holochain that the shipyard has not been tested with then it might break. That's the downside of choosing your own versions.

**Comment by tibetsprague** [comment]
Thank you!
